package views;

import java.util.Date;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.LoaiDep;
import services.ILoaiDepService;
import services.impl.LoaiDepService;
import swing.Table;
import utilities.Helper;

/**
 *
 * @author dell
 */
public class FrmLoaiDepOK extends javax.swing.JPanel {
    
    private ILoaiDepService loaidepSV;
    private DefaultTableModel defaultTableModel;
    private Helper helper;
    private SimpleDateFormat formatD = new SimpleDateFormat("dd-MM-yyyy");
    private ButtonGroup btn = new ButtonGroup();

    /**
     * Creates new form FrmLoaiDepOK
     */
    public FrmLoaiDepOK() {
        initComponents();
        initComponents();
        loaidepSV = new LoaiDepService();
        helper = new Helper();
        btn.add(rd_DangKinhDoanh);
        btn.add(rd_NgungKinhDoanh);
        LoadTabale(loaidepSV.getAll());
        Table.apply(jScrollPane1, Table.TableType.MULTI_LINE);
    }
    
    public void LoadTabale(List<LoaiDep> list) {
        int stt = 1;
        defaultTableModel = (DefaultTableModel) tb_Table.getModel();
        defaultTableModel.setRowCount(0);
        for (LoaiDep x : list) {
            Object[] row = {
                stt++, x.getMa(), x.getTen(), formatD.format(x.getNgayThem()), formatD.format(x.getNgaySuaCuoi()),
                x.getTrangThai() == 0 ? "Đang Kinh Doanh" : "Ngừng Kinh Doanh"
            };
            defaultTableModel.addRow(row);
        }
        lbl_Total.setText("Total:" + list.size());
    }

    private boolean checkNull() {
        if (helper.checkNull(txt_Ten, "Tên")
                || helper.checkRegex(txt_Ten, "(\\S+ )*\\S+", "Tên không hợp lệ!")) {
            return true;
        } else if (!rd_DangKinhDoanh.isSelected() && !rd_NgungKinhDoanh.isSelected()) {
            helper.error(this, "chưa chọn trạng thái");
            return true;
        }
        return false;

    }

    private LoaiDep getForm() {
        LoaiDep loaiDep = new LoaiDep();
        String result;
        for (int i = 0; i < loaidepSV.getAll().size() + 1; i++) {
            result = "LD" + i;
            if (loaidepSV.getObj(result) == null) {
                loaiDep.setMa(result);
                break;
            } else {
                continue;
            }
        }
        String ten = txt_Ten.getText();
        int trangthai;
        if (rd_DangKinhDoanh.isSelected()) {
            trangthai = 0;
        } else {
            trangthai = 1;
        }
        loaiDep.setTen(ten);
        loaiDep.setNgayThem(new Date());
        loaiDep.setNgaySuaCuoi(new Date());
        loaiDep.setTrangThai(trangthai);
        return loaiDep;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_Them = new swing.Button();
        btn_CapNhap = new swing.Button();
        txt_Ten = new swing.TextField();
        lbl_Total = new javax.swing.JLabel();
        txt_Ma = new swing.TextField();
        rd_DangKinhDoanh = new swing.RadioButtonCustom();
        rd_NgungKinhDoanh = new swing.RadioButtonCustom();
        txt_TimKiem = new swing.TextField();
        tableScrollButton1 = new swing.TableScrollButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_Table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        btn_Them.setText("Thêm");
        btn_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemActionPerformed(evt);
            }
        });

        btn_CapNhap.setText("Cập Nhập");
        btn_CapNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CapNhapActionPerformed(evt);
            }
        });

        txt_Ten.setLabelText("Tên:");

        lbl_Total.setBackground(new java.awt.Color(204, 204, 204));
        lbl_Total.setForeground(new java.awt.Color(255, 0, 0));
        lbl_Total.setText("Total: 0");

        txt_Ma.setEditable(false);
        txt_Ma.setLabelText("Mã:");

        rd_DangKinhDoanh.setSelected(true);
        rd_DangKinhDoanh.setText("Đang Kinh Doanh");

        rd_NgungKinhDoanh.setText("Ngừng Kinh Doanh");

        txt_TimKiem.setLabelText("Tìm Kiếm:");
        txt_TimKiem.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txt_TimKiemCaretUpdate(evt);
            }
        });

        tb_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã", "Tên", "Ngày Thêm", "Ngày Sửa Cuối", "Trạng Thái"
            }
        ));
        tb_Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_Table);

        tableScrollButton1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("LOẠI DÉP");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_TimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt_Ma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt_Ten, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rd_DangKinhDoanh, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rd_NgungKinhDoanh, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_Them, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_CapNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(tableScrollButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
                        .addGap(32, 32, 32))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tableScrollButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_Ma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rd_DangKinhDoanh, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_Ten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rd_NgungKinhDoanh, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_Total)
                            .addComponent(txt_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_Them, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_CapNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(159, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemActionPerformed

        if (checkNull()) {
            return;
        }
        LoaiDep loaidep = getForm();
        this.loaidepSV.save(loaidep);
        LoadTabale(loaidepSV.getAll());
        helper.alert(this, "Thêm thành công");
    }//GEN-LAST:event_btn_ThemActionPerformed

    private void btn_CapNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CapNhapActionPerformed
        int row = tb_Table.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Chọn 1 dòng sản phẩm");
            return;
        }
        LoaiDep loaidep = getForm();
        LoaiDep loai = loaidepSV.getObj(txt_Ma.getText().trim());
        loai.setTen(loaidep.getTen());
        loai.setNgaySuaCuoi(loaidep.getNgaySuaCuoi());
        loai.setTrangThai(loaidep.getTrangThai());
        this.loaidepSV.save(loai);
        LoadTabale(loaidepSV.getAll());
        JOptionPane.showMessageDialog(this, "Sửa thành công");
    }//GEN-LAST:event_btn_CapNhapActionPerformed

    private void tb_TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_TableMouseClicked
        int row = tb_Table.getSelectedRow();
        LoaiDep loaidep = loaidepSV.getAll().get(row);
        txt_Ma.setText(loaidep.getMa());
        txt_Ten.setText(loaidep.getTen());
        rd_DangKinhDoanh.setSelected(loaidep.getTrangThai() == 0);
        rd_DangKinhDoanh.setSelected(loaidep.getTrangThai() == 1);
    }//GEN-LAST:event_tb_TableMouseClicked

    private void txt_TimKiemCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txt_TimKiemCaretUpdate
        LoadTabale(loaidepSV.findByName(txt_TimKiem.getText()));
    }//GEN-LAST:event_txt_TimKiemCaretUpdate


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.Button btn_CapNhap;
    private swing.Button btn_Them;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_Total;
    private swing.RadioButtonCustom rd_DangKinhDoanh;
    private swing.RadioButtonCustom rd_NgungKinhDoanh;
    private swing.TableScrollButton tableScrollButton1;
    private javax.swing.JTable tb_Table;
    private swing.TextField txt_Ma;
    private swing.TextField txt_Ten;
    private swing.TextField txt_TimKiem;
    // End of variables declaration//GEN-END:variables
}
