package views;

import java.time.Instant;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.NhaSX;
import services.INhaSXService;
import services.impl.NhaSXService;
import utilities.Helper;

/**
 *
 * @author chiltk
 */
public class FrmNSX extends javax.swing.JFrame {

    private DefaultTableModel dtm;
    private INhaSXService iNhaSXService;
    private Helper helper;

    public FrmNSX() {
        initComponents();
        iNhaSXService = new NhaSXService();
        loadToTable(iNhaSXService.getAll());
        helper = new Helper();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_Capnhat = new swing.Button();
        txt_Ma = new swing.TextField();
        txt_Ten = new swing.TextField();
        txt_Ngaythem = new swing.TextField();
        txt_Ngaysua = new swing.TextField();
        rd_Ngungnhap = new swing.RadioButtonCustom();
        rd_Dangnhap = new swing.RadioButtonCustom();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBang = new javax.swing.JTable();
        btn_Them = new swing.Button();
        txt_Timkiem = new swing.TextField();
        lbl_Total = new javax.swing.JLabel();
        btn_Xoa = new swing.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_Capnhat.setBackground(new java.awt.Color(153, 153, 153));
        btn_Capnhat.setForeground(new java.awt.Color(255, 255, 255));
        btn_Capnhat.setLabel("Cập nhật");
        btn_Capnhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CapnhatActionPerformed(evt);
            }
        });

        txt_Ma.setLabelText("Mã");

        txt_Ten.setLabelText("Tên NSX");

        txt_Ngaythem.setLabelText("Ngày Thêm");

        txt_Ngaysua.setLabelText("Ngày Sửa Cuối");

        rd_Ngungnhap.setText(" Ngừng nhập hàng");
        rd_Ngungnhap.setActionCommand("");

        rd_Dangnhap.setText("Đang nhập hàng");

        tblBang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã", "Tên", "Ngày thêm", "Ngày  sửa cuối", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblBang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBang);

        btn_Them.setBackground(new java.awt.Color(153, 153, 153));
        btn_Them.setForeground(new java.awt.Color(255, 255, 255));
        btn_Them.setLabel("Thêm");
        btn_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemActionPerformed(evt);
            }
        });

        txt_Timkiem.setLabelText("Tìm kiếm");
        txt_Timkiem.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txt_TimkiemCaretUpdate(evt);
            }
        });

        lbl_Total.setForeground(new java.awt.Color(255, 0, 51));
        lbl_Total.setText("Total: 0");

        btn_Xoa.setBackground(new java.awt.Color(153, 153, 153));
        btn_Xoa.setForeground(new java.awt.Color(255, 255, 255));
        btn_Xoa.setText("Xóa");
        btn_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(btn_Them, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(btn_Capnhat, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_Ma, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                                    .addComponent(txt_Ngaythem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_Ngaysua, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                                    .addComponent(txt_Ten, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rd_Dangnhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rd_Ngungnhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_Timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(168, 168, 168)
                        .addComponent(lbl_Total, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Ma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Ten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rd_Dangnhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_Ngaysua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Ngaythem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(rd_Ngungnhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Them, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Capnhat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_Timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Total))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_TimkiemCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txt_TimkiemCaretUpdate
        loadToTable(iNhaSXService.findByName(txt_Timkiem.getText()));
    }//GEN-LAST:event_txt_TimkiemCaretUpdate

    private void tblBangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBangMouseClicked
        int row = tblBang.getSelectedRow();
        NhaSX n = iNhaSXService.getAll().get(row);
        txt_Ma.setText(n.getMa());
        txt_Ten.setText(n.getTen());
        txt_Ngaythem.setText(n.getNgayThem() + "");
        txt_Ngaysua.setText(n.getNgaySuaCuoi() + "");
        rd_Dangnhap.setSelected(n.getTrangThai() == 0);
        rd_Ngungnhap.setSelected(n.getTrangThai() == 1);
    }//GEN-LAST:event_tblBangMouseClicked

    private void btn_CapnhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CapnhatActionPerformed
        int row = tblBang.getSelectedRow();
        NhaSX n = iNhaSXService.getObj(tblBang.getValueAt(row, 1).toString());
        if (checkNull()) {
            return;
        }
        n.setMa(txt_Ma.getText());
        n.setTen(txt_Ten.getText());
        n.setNgayThem(new Date());
        n.setNgaySuaCuoi(new Date());
        if (rd_Dangnhap.isSelected()) {
            n.setTrangThai(0);
        } else {
            n.setTrangThai(1);
        }
        iNhaSXService.save(n);
        loadToTable(iNhaSXService.getAll());
        helper.alert(this, "Sửa thành công!");
        clear();
    }//GEN-LAST:event_btn_CapnhatActionPerformed

    private void btn_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemActionPerformed
        NhaSX n = new NhaSX();
        if (checkNull()) {
            return;
        }
        String result;
        for (int i = 0; i < iNhaSXService.getAll().size() + 1; i++) {
            result = "NX" + i;
            if (iNhaSXService.getObj(result) == null) {
                n.setMa(result);
                break;
            } else {
                continue;
            }
        }
        if (iNhaSXService.getObj(txt_Ma.getText()) == null) {
            if (iNhaSXService.getObj(txt_Ma.getText()) != null) {
                JOptionPane.showMessageDialog(this, "Da ton tai !");
                return;
            }
            n.setMa(txt_Ma.getText());
            n.setTen(txt_Ten.getText());
            n.setNgayThem(new Date());
            n.setNgaySuaCuoi(new Date());
            if (rd_Dangnhap.isSelected()) {
                n.setTrangThai(0);
            } else {
                n.setTrangThai(1);
            }
            iNhaSXService.save(n);
            loadToTable(iNhaSXService.getAll());
            helper.alert(this, "Thêm thành công!");
            clear();
        }
    }//GEN-LAST:event_btn_ThemActionPerformed

    private void btn_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaActionPerformed
         int row = tblBang.getSelectedRow();
        NhaSX n = iNhaSXService.getObj(tblBang.getValueAt(row, 1).toString());
        iNhaSXService.delete(n);
        loadToTable(iNhaSXService.getAll());
    }//GEN-LAST:event_btn_XoaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmNSX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmNSX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmNSX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmNSX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmNSX().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.Button btn_Capnhat;
    private swing.Button btn_Them;
    private swing.Button btn_Xoa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_Total;
    private swing.RadioButtonCustom rd_Dangnhap;
    private swing.RadioButtonCustom rd_Ngungnhap;
    private javax.swing.JTable tblBang;
    private swing.TextField txt_Ma;
    private swing.TextField txt_Ngaysua;
    private swing.TextField txt_Ngaythem;
    private swing.TextField txt_Ten;
    private swing.TextField txt_Timkiem;
    // End of variables declaration//GEN-END:variables
    private void loadToTable(List<NhaSX> list) {
        int stt = 1;
        dtm = (DefaultTableModel) tblBang.getModel();
        dtm.setRowCount(0);
        for (NhaSX x : list) {
            dtm.addRow(new Object[]{
                stt++,
                x.getMa(),
                x.getTen(),
                x.getNgayThem(), x.getNgaySuaCuoi(), x.getTrangThai()
            });
        }
        lbl_Total.setText("Total: " + list.size());
    }

    private boolean checkNull() {
        if (helper.checkNull(txt_Ma, "Mã")
                || helper.checkRegex(txt_Ma, "^\\w[a-zA-Z@#0-9.]*$", "Mã không chứa dấu cách!")
                || helper.checkNull(txt_Ten, "Tên")
                || helper.checkRegex(txt_Ten, "(\\S+ )*\\S+", "Tên không hợp lệ!")
                || helper.checkNull(txt_Ngaythem, "Ngày thêm")
                || helper.checkNull(txt_Ngaysua, "Ngày sửa")) {
            return true;
        } else if (!rd_Ngungnhap.isSelected() && !rd_Dangnhap.isSelected()) {
            helper.error(this, "chưa chọn trạng thái");
            return true;
        }
        return false;

    }

    public void clear() {
        txt_Ma.setText("");
        txt_Ten.setText("");
        txt_Ngaythem.setText("");
        txt_Ngaysua.setText("");
        rd_Dangnhap.clearSelection();
        rd_Ngungnhap.clearSelection();
    }
}
