package views;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.Size;
import services.ISizeService;
import services.impl.SizeService;
import utilities.Helper;

/**
 *
 * @author KenTizz
 */
public class FrmSize extends javax.swing.JFrame {

    /**
     * Creates new form SizeFrame
     */
    private Helper helper;
    private ISizeService sizeService = new SizeService();
    private DefaultTableModel tableModel = new DefaultTableModel();
    private ButtonGroup group = new ButtonGroup();
    private SimpleDateFormat format = new SimpleDateFormat("dd-MM-yyyy");

    public FrmSize() {
        initComponents();
        tb_DanhSach.getTableHeader().setReorderingAllowed(false);
        group.add(rd_DangKinhDoanh);
        group.add(rd_NgungKinhDoanh);
        loadData(sizeService.getListSize());
        helper = new Helper();
    }

    public void loadData(List<Size> list) {
        tableModel = (DefaultTableModel) tb_DanhSach.getModel();
        tableModel.setRowCount(0);
        for (Size s : list) {
            tableModel.addRow(new Object[]{
                s.getMa(),
                s.getKichCo(),
                format.format(s.getNgayThem()),
                format.format(s.getNgaySuaCuoi()),
                s.getTrangThai() == 0 ? "Đang kinh doanh" : "Ngừng kinh doanh"
            });
        }
    }

    public boolean check() {

        if (helper.checkNull(txt_KichCo, "Kích cỡ")) {
            return true;
        } else if (!rd_DangKinhDoanh.isSelected() && !rd_NgungKinhDoanh.isSelected()) {
            helper.error(this, "chưa chọn trạng thái");
            return true;
        } else {
            try {
                float f = Float.parseFloat(txt_KichCo.getText().trim());
            } catch (NumberFormatException e) {
                helper.error(this, "Kích cỡ không chứa chữ !");
                return true;
            }
            return false;
        }
    }

    public void clear() {
        txt_Ma.setText("");
        txt_KichCo.setText("");
        group.clearSelection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tb_DanhSach = new javax.swing.JTable();
        txt_KichCo = new swing.TextField();
        txt_Ma = new swing.TextField();
        rd_DangKinhDoanh = new swing.RadioButtonCustom();
        rd_NgungKinhDoanh = new swing.RadioButtonCustom();
        btn_update = new swing.Button();
        btn_add = new swing.Button();
        txt_search = new swing.TextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tb_DanhSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã", "Kích cỡ", "Ngày thêm", "Ngày sửa cuối", "Trạng thái"
            }
        ));
        tb_DanhSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_DanhSachMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_DanhSach);

        txt_KichCo.setToolTipText("");
        txt_KichCo.setLabelText("Kích cỡ :");

        txt_Ma.setEditable(false);
        txt_Ma.setToolTipText("");
        txt_Ma.setLabelText("Mã :");

        rd_DangKinhDoanh.setText("Đang kinh doanh");

        rd_NgungKinhDoanh.setText("Ngừng kinh doanh");

        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn_add.setText("Add");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        txt_search.setLabelText("Search");
        txt_search.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txt_searchCaretUpdate(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_Ma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_KichCo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(52, 52, 52))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rd_DangKinhDoanh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(rd_NgungKinhDoanh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_add, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addGap(399, 399, 399))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_Ma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_KichCo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rd_DangKinhDoanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rd_NgungKinhDoanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tb_DanhSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_DanhSachMouseClicked
        // TODO add your handling code here:
        int row = tb_DanhSach.getSelectedRow();
        txt_Ma.setText(tb_DanhSach.getValueAt(row, 0).toString());
        txt_KichCo.setText(tb_DanhSach.getValueAt(row, 1).toString());
        if (tb_DanhSach.getValueAt(row, 4).equals("Đang kinh doanh")) {
            rd_DangKinhDoanh.setSelected(true);
        } else {
            rd_NgungKinhDoanh.setSelected(true);
        }
    }//GEN-LAST:event_tb_DanhSachMouseClicked

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        // TODO add your handling code here:
        Size size = new Size();
        if (check()) {
            return;
        }
        String result;
        for (int i = 0; i < sizeService.getListSize().size() + 1; i++) {
            result = "Size" + i;
            if (sizeService.getObj(result) == null) {
                size.setMa(result);
                break;
            } else {
                continue;
            }
        }
        size.setKichCo(Float.valueOf(txt_KichCo.getText()));
        size.setNgayThem(new Date());
        size.setNgaySuaCuoi(new Date());
        if (rd_DangKinhDoanh.isSelected()) {
            size.setTrangThai(0);
        } else {
            size.setTrangThai(1);
        }
        sizeService.save(size);
        loadData(sizeService.getListSize());
        helper.alert(this, "Thêm thành công");
        clear();
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // TODO add your handling code here:
        int row = tb_DanhSach.getSelectedRow();
        Size size = sizeService.getObj(tb_DanhSach.getValueAt(row, 0).toString());
        if (check()) {
            return;
        }
        size.setKichCo(Float.valueOf(txt_KichCo.getText()));
        size.setNgaySuaCuoi(new Date());
        if (rd_DangKinhDoanh.isSelected()) {
            size.setTrangThai(0);
        } else {
            size.setTrangThai(1);
        }
        sizeService.save(size);
        loadData(sizeService.getListSize());
        helper.alert(this, "Sửa thành công");
        clear();
    }//GEN-LAST:event_btn_updateActionPerformed

    private void txt_searchCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txt_searchCaretUpdate
        // TODO add your handling code here:
        clear();
        loadData(sizeService.findByName(txt_search.getText()));
    }//GEN-LAST:event_txt_searchCaretUpdate

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSize.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSize.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSize.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSize.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmSize().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.Button btn_add;
    private swing.Button btn_update;
    private javax.swing.JScrollPane jScrollPane1;
    private swing.RadioButtonCustom rd_DangKinhDoanh;
    private swing.RadioButtonCustom rd_NgungKinhDoanh;
    private javax.swing.JTable tb_DanhSach;
    private swing.TextField txt_KichCo;
    private swing.TextField txt_Ma;
    private swing.TextField txt_search;
    // End of variables declaration//GEN-END:variables
}
