package views;

import java.awt.Color;
import java.util.List;
import models.HoaDon;
import models.HoaDonChiTiet;
import services.IHoaDonCTService;
import services.IHoaDonService;
import services.impl.HoaDonCTService;
import services.impl.HoaDonService;
import swing.ModelPieChart;
import swing.PieChart;
import ui.ModelCard;

/**
 *
 * @author VU NGUYEN HUONG
 */
public class FrmThongKeHoaDon extends javax.swing.JPanel {

    private IHoaDonService iHoaDonService = new HoaDonService();
    private IHoaDonCTService iHoaDonCTService = new HoaDonCTService();
    
    public FrmThongKeHoaDon() {
        initComponents();
        List<HoaDonChiTiet> listHDCT = iHoaDonCTService.findByTT(1);
        Double doanhThu = 0.0;
        try {
            for (HoaDonChiTiet x : listHDCT) {
                if (x.getHoaDon().getKhuyenMai() == null) {
                    doanhThu += x.getDonGia().doubleValue() * x.getSoLuong()  - x.getHoaDon().getDiemTichLuy() * 1000;
                } else {
                    doanhThu += x.getDonGia().doubleValue() * x.getSoLuong()  - x.getHoaDon().getDiemTichLuy() * 1000 - (x.getDonGia().doubleValue() * x.getSoLuong()) / 100 * x.getHoaDon().getKhuyenMai().getPhantramgiam();
                }
            }
        } catch (Exception e) {
        }
        tong.setData(new ModelCard("Tổng đơn hàng", iHoaDonService.getAll().size(), null));
        chuatt.setData(new ModelCard("Chưa thanh toán", iHoaDonService.getByTT(0).size(), null));
        datt.setData(new ModelCard("Đã thanh toán", iHoaDonService.getByTT(1).size(), null));
        tongdoanhthu.setData(new ModelCard("Tổng doanh thu", doanhThu, null));
    
        pieChart1.setChartType(PieChart.PeiChartType.DEFAULT);
        pieChart1.addData(new ModelPieChart("Tigher", 150, new Color(23, 126, 238)));
        pieChart1.addData(new ModelPieChart("ABC", 100, new Color(221, 65, 65)));
        pieChart1.addData(new ModelPieChart("Vita", 60, new Color(196, 151, 58)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tongdoanhthu = new swing.Card();
        tong = new swing.Card();
        jLabel1 = new javax.swing.JLabel();
        chuatt = new swing.Card();
        datt = new swing.Card();
        pieChart1 = new swing.PieChart();

        setBackground(new java.awt.Color(255, 255, 255));

        tongdoanhthu.setBackground(new java.awt.Color(60, 195, 0));
        tongdoanhthu.setColorGradient(new java.awt.Color(0, 255, 51));

        tong.setColorGradient(new java.awt.Color(211, 28, 215));

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(4, 72, 210));
        jLabel1.setText("Thống kê / Hóa đơn");

        chuatt.setBackground(new java.awt.Color(10, 30, 214));
        chuatt.setColorGradient(new java.awt.Color(72, 111, 252));

        datt.setBackground(new java.awt.Color(194, 85, 1));
        datt.setColorGradient(new java.awt.Color(255, 212, 99));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tong, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(chuatt, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(datt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                            .addComponent(tongdoanhthu, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(pieChart1, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(pieChart1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(chuatt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(datt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tongdoanhthu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.Card chuatt;
    private swing.Card datt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private swing.PieChart pieChart1;
    private swing.Card tong;
    private swing.Card tongdoanhthu;
    // End of variables declaration//GEN-END:variables
}
