package views;

import swing.ButtonUI;
import swing.MyTextField;
import java.awt.Color;
import java.awt.Font;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.UUID;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import models.NguoiDung;
import net.miginfocom.swing.MigLayout;
import services.INguoiDungService;
import services.impl.NguoiDungService;
import utilities.Helper;
import utilities.SendMailUltil;

/**
 *
 * @author KenTizz
 */
public class MainResetPassFrame extends javax.swing.JFrame {

    INguoiDungService iNguoiDungService = new NguoiDungService();
    Helper helper = new Helper();
    MyTextField txtUser = new MyTextField();
    MyTextField txtEmail = new MyTextField();
    MyTextField txtcapcha = new MyTextField();
    JLabel lblcapCha = new JLabel();
    SendMailUltil mailUltil = new SendMailUltil();

    /**
     * Creates new form mainReset
     */
    public MainResetPassFrame() {
        initComponents();
        init();
    }

    public void init() {
        reset.setLayout(new MigLayout("wrap", "push[center]push", "push[]25[]10[]1[]1[]25[]10[]push"));
        JLabel label = new JLabel("Reset Password");
        label.setFont(new Font("sansserif", 1, 30));
        label.setForeground(new Color(176, 196, 222));
        reset.add(label);
        txtUser.setPrefixIcon(new ImageIcon(getClass().getResource("/icons/use.png")));
        txtUser.setHint("Tên đăng nhập");
        reset.add(txtUser, "w 60%");
        txtEmail.setPrefixIcon(new ImageIcon(getClass().getResource("/icons/mail.png")));
        txtEmail.setHint("Email");
        reset.add(txtEmail, "w 60%");
        lblcapCha.setText(UUID.randomUUID().toString().substring(30, 36));
        lblcapCha.setFont(new Font("sansserif", 1, 15));
        lblcapCha.setForeground(new Color(255, 0, 0));
        reset.add(lblcapCha, "w 60%");
        txtcapcha.setPrefixIcon(new ImageIcon(getClass().getResource("/icons/capcha.png")));
        txtcapcha.setHint("Capcha");
        reset.add(txtcapcha, "w 60%");
        ButtonUI submit = new ButtonUI();
        submit.setForeground(new Color(250, 250, 250));
        submit.setBackground(new Color(176, 196, 222));
        reset.add(submit);
        submit.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String userName = txtUser.getText().trim();
                String email = txtEmail.getText().trim();
                String capcha = lblcapCha.getText().trim();
                String newPassword = UUID.randomUUID().toString().substring(0, 8);
                NguoiDung nd = iNguoiDungService.getObj(userName);
                resetPass();
            }
        });
        submit.setText("SUBMIT");
        reset.add(submit, "w 40%, h 40");
        ButtonUI cancel = new ButtonUI();
        cancel.setBackground(new Color(176, 196, 222));
        cancel.setForeground(new Color(250, 250, 250));
        cancel.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                new MainLoginFrame().setVisible(true);
                dispose();
            }
        });
        cancel.setText("CANCEL");
        reset.add(cancel, "w 40%, h 40");

    }

    public void resetPass() {
        String userName = txtUser.getText().trim();
        String email = txtEmail.getText().trim();
        String lbl_reset_capcha = lblcapCha.getText().trim();
        String txt_reset_capcha = txtcapcha.getText().trim();
        String newPassword = UUID.randomUUID().toString().substring(0, 8);
        NguoiDung nd = iNguoiDungService.getObj(userName);
        if (nd == null) {
            helper.error(this, "Tên đăng nhập không tồn tại!");
        } else {
            if (nd.getEmail().equals(email)) {
                if (!txt_reset_capcha.equals(lbl_reset_capcha)) {
                    helper.error(this, "Mã capcha không chính xác!");
                } else {
                    if (helper.confirm(this, "Mật khẩu mới sẽ được gửi đến " + email + ". Chọn YES để xác nhận!")) {
                        nd.setMatKhau(newPassword);
                        iNguoiDungService.save(nd);
                        helper.alert(this, mailUltil.sendEmail(email, "[MWC_STORE] Mật khẩu đã được đặt lại!", "Xin chào, mật khẩu mới của bạn là: " + newPassword));
                        lblcapCha.setText(UUID.randomUUID().toString().substring(30, 36));
                    }
                }
            } else {
                helper.error(this, "Email không chính xác!");
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reset = new javax.swing.JPanel();
        title = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        reset.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout resetLayout = new javax.swing.GroupLayout(reset);
        reset.setLayout(resetLayout);
        resetLayout.setHorizontalGroup(
            resetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );
        resetLayout.setVerticalGroup(
            resetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        getContentPane().add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 540));

        title.setBackground(new java.awt.Color(176, 196, 222));
        title.setFocusCycleRoot(true);

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(245, 245, 245));
        jLabel1.setText("To recover your password");

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(245, 245, 245));
        jLabel2.setText(" please fill out all the information");

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(245, 245, 245));
        jLabel3.setText("Forgot password !");

        javax.swing.GroupLayout titleLayout = new javax.swing.GroupLayout(title);
        title.setLayout(titleLayout);
        titleLayout.setHorizontalGroup(
            titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleLayout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addGroup(titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titleLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titleLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(113, 113, 113))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titleLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(76, 76, 76))))
        );
        titleLayout.setVerticalGroup(
            titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleLayout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(jLabel3)
                .addGap(64, 64, 64)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(192, Short.MAX_VALUE))
        );

        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 370, 540));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainResetPassFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainResetPassFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainResetPassFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainResetPassFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainResetPassFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel reset;
    private javax.swing.JPanel title;
    // End of variables declaration//GEN-END:variables
}
